version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: devtools-protocol
    versions:
    - 0.0.839267
    - 0.0.848227
  - dependency-name: eslint
    versions:
    - 7.16.0
  - dependency-name: typescript
    versions:
    - 4.0.5
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.3.0
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.0
