sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
env:
  - CHROME_BIN=/usr/bin/google-chrome-beta
