jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: node
      - uses: browser-actions/setup-chrome@v2
        id: setup-chrome
      - run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
      - run: yarn checkjs
      - run: yarn lint
      - run: yarn test
name: main
on:
  - pull_request
  - push
